         --lAB-3

		 --PART-A

CREATE TABLE CRICKET(
NAME VARCHAR(50),
CITY VARCHAR(50),
AGE INT
);

INSERT INTO CRICKET VALUES('SACHIN TENDULHAR','MUMBAI',30)
INSERT INTO CRICKET VALUES('RAHUL DRAVID','BOMBAY',35)
INSERT INTO CRICKET VALUES('M.S. DHONI','JHARKHAND',31)
INSERT INTO CRICKET VALUES('SURESH RAINA','GUJARAT',30)

SELECT * FROM CRICKET


--1. Create table Worldcup from cricket with all the columns and data.

SELECT * INTO WORLDCUP
FROM CRICKET

--2. Create table T20 from cricket with first two columns with no data. 

SELECT NAME,CITY INTO T20
FROM CRICKET 
WHERE 1=2;

--3. Create table IPL From Cricket with No Data

SELECT * INTO IPL
FROM CRICKET
WHERE 2<1;